apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace | default "default" }}
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: {{ .Values.secretManager.secretId }}
      versionId: {{ .Values.secretManager.versionId }}