{{- if .Values.app.sidekiq.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace | default "default" }}
  name: "{{ .Values.app.name }}-sidekiq"
  labels:
    env: {{ .Values.app.env }}
    name: "{{ .Values.app.name }}-sidekiq"
    tags.datadoghq.com/env: {{ .Values.app.env }}
    tags.datadoghq.com/service: "{{ .Values.app.name }}-sidekiq"
spec:
  selector:
    matchLabels:
      env: {{ .Values.app.env }}
      name: "{{ .Values.app.name }}-sidekiq"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 40%
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        env: {{ .Values.app.env }}
        name: "{{ .Values.app.name }}-sidekiq"
        tags.datadoghq.com/env: {{ .Values.app.env }}
        tags.datadoghq.com/service: "{{ .Values.app.name }}-sidekiq"
    spec:
      {{- if .Values.app.sidekiq.service_account }}
      serviceAccountName: "{{ .Values.app.name }}-{{ .Values.app.sidekiq.service_account }}"
      {{- end }}
      containers:
        - name: "{{ .Values.app.name }}-sidekiq"
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.app.image_pull_policy | default "IfNotPresent" }}
          {{- if .Values.app.sidekiq.lifecycle}}
          lifecycle:
            preStop:
               exec: 
                command: 
                {{- range .Values.app.sidekiq.lifecycle.preStop.command }}
                 - {{.}}
                {{- end}}
          {{- end }}
          env:
          - name: role
            value: "sidekiq"
          envFrom:
          - secretRef:
              name: {{ .Values.app.name }}
          {{- if .Values.app.port }}
          ports:
            - containerPort: {{ .Values.app.port }}
          {{- end }}
          {{- if .Values.app.sidekiq.healthcheck }}
          livenessProbe:
            exec:
              command:
                {{- range .Values.app.sidekiq.healthcheck_command }}
                 - {{.}}
                {{- end}}              
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                {{- range .Values.app.sidekiq.healthcheck_command }}
                 - {{.}}
                {{- end}} 
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          {{- end }}
          resources:
            limits:
              {{- if (gt (.Values.app.sidekiq.cpu_limit | default 0.0) 0.0) }}
              cpu: {{.Values.app.sidekiq.cpu_limit}}m
              {{- end }}
              {{- if (gt (.Values.app.sidekiq.mem_limit | default 0.0) 0.0) }}
              memory: {{.Values.app.sidekiq.mem_limit}}Mi
              {{- end }}
            requests:
              {{- if (gt (.Values.app.sidekiq.cpu_required | default 0.0) 0.0) }}
              cpu: {{.Values.app.sidekiq.cpu_required}}m
              {{- end }}
              {{- if (gt (.Values.app.sidekiq.mem_required | default 0.0) 0.0) }}
              memory: {{.Values.app.sidekiq.mem_required}}Mi
              {{- end }}
      {{- if .Values.app.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.app.imagePullSecrets }}
      {{- end}}
      {{- if .Values.app.node_selectors }}
      nodeSelector: 
        {{- range $key, $val := .Values.app.node_selectors }}
        {{ $key }}: {{ $val }}
        {{- end}}
      {{- end}}
{{- end }}