{{- if ne .Values.app.region  "us-west-2"  }}
{{- if eq .Values.app.name  "order" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.app.name }}-clean-manual-orders"
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: "{{ .Values.app.name }}-clean-manual-orders"
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            command:
            - /bin/bash
            - -c
            - -l
            - 'cd /var/app/current && bin/init-config.sh && bundle exec rake cron:clean_manual_orders --silent'
            envFrom:
            - secretRef:
                name: {{ .Values.app.name }}
          restartPolicy: Never
          {{- if .Values.app.node_selectors }}
          nodeSelector: 
            {{- range $key, $val := .Values.app.node_selectors }}
            {{ $key }}: {{ $val }}
            {{- end}}
          {{- end}}
{{- end }}
{{- end }}
