{{- if eq .Values.app.name  "shipment" }}
{{- if ne .Values.app.region  "us-west-2"  }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.app.name }}-pod-export"
spec:
  schedule: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: "{{ .Values.app.name }}-pod-export"
            image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
            command:
            - /bin/bash
            - -c
            - -l
            - 'cd /var/app/current && bin/init-config.sh && bundle exec rake csv_export:pod_data --silent'
            envFrom:
            - secretRef:
                name: {{ .Values.app.name }}
          restartPolicy: Never
          {{- if .Values.app.node_selectors }}
          nodeSelector: 
            {{- range $key, $val := .Values.app.node_selectors }}
            {{ $key }}: {{ $val }}
            {{- end}}
          {{- end}}
{{- end }}
{{- end }}
