app:
  region: us-west-2
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 3
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1024
    cpu_limit: 400
    cpu_required: 200
  sidekiq:
    lifecycle:
      preStop:
       command:
         - /bin/sh
         - '-c'
         - |
           kill -TERM $(ps -aux| grep -i 'sidekiq' | awk 'NR==1{print $2}')  
    service_account: "sidekiq-sa"
    healthcheck: true
    healthcheck_command:
       - sh
       - '-c'
       - |
         if [ $(($(cat /sys/fs/cgroup/memory/memory.usage_in_bytes)*100/$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes))) -gt 75 ]; then exit 1;fi    
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 2
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2000
    mem_required: 400
    cpu_limit: 500
    cpu_required: 200
  qlogger:
    healthcheck: false
    enabled: false
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  kafka:
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 0
    mem_required: 400
    cpu_limit: 0
    cpu_required: 100
  namespace: dev
  name: order
  port: 3000
  env: dev
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: dev
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: pre-deploy/pre-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.us-west-2.amazonaws.com/order-quincus-images
  tag: "cdf6b71"
service:
  type: ClusterIP
secretManager:
  secretId: dev/order
  versionId: 7da3ee65-eb8d-4538-b034-17c5c0423215
ingress:
  enabled: true
  hostName_noram: api.order.dev-noram.quincus.com
  hostName: api.order.dev.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dispatch.dev-noram.quincus.com, https://shipment.dev-noram.quincus.com, https://pricing.dev-noram.quincus.com, https://common.dev-noram.quincus.com, https://order.dev-noram.quincus.com, https://dev-noram.quincus.com, https://dispatch.dev.quincus.com, https://shipment.dev.quincus.com, https://pricing.dev.quincus.com, https://common.dev.quincus.com, https://order.dev.quincus.com, https://dev.quincus.com, https://quincus.dev.qship.quincus.com,http://quincus.qship.local.com:3004, http://localhost:3000, http://localhost:3004, https://dev.quincus.app"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform,timeout"
redis:
  architecture: standalone
  enabled: true
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: dev
      node-type: spot
  auth:
    enabled: false
#deployed on Tue Aug  8 04:04:49 UTC 2023