replicaCount: 1
app:
  region: ap-southeast-1
  namespace: dev
  name: shipment-nextgen
  port: 8080
  env: dev
  image_pull_policy: IfNotPresent
  mem_limit: 0
  mem_required: 1024
  cpu_limit: 0
  cpu_required: 500
  node_selectors:
    environment: dev
    node-type: spot
  hpa:
    minReplicas: 1
    maxReplicas: 2
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/shipment-nextgen-be
  tag: "6.0.0-SNAPSHOT-09344e5"
service:
  type: ClusterIP
ingress:
  enabled: true
  hostName_noram: api.shipment-nextgen.dev-noram.quincus.com
  hostName: api.shipment-nextgen.dev.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "502,503,504"
#deployed on Tue Aug  8 04:07:58 UTC 2023