replicaCount: 1
app:
  namespace: staging
  name: shipment-nextgen
  port: 8080
  env: staging
  image_pull_policy: IfNotPresent
  mem_limit: 0
  mem_required: 1024
  cpu_limit: 0
  cpu_required: 500
  node_selectors:
    environment: staging
    node-type: spot
  hpa:
    minReplicas: 1
    maxReplicas: 2
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/shipment-nextgen-be
  tag: "6.0.0-SNAPSHOT-05914fc"
service:
  type: ClusterIP
ingress:
  enabled: true
  hostName: api.shipment-nextgen.staging.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "502,503,504"
#deployed on Mon Aug  7 15:43:24 UTC 2023