replicaCount: 1
app:
  region: us-west-2
  namespace: prod
  name: logisticengine-service
  port: 8081
  env: prod
  image_pull_policy: IfNotPresent
  mem_limit: 6000
  mem_required: 2000
  cpu_limit: 4000
  cpu_required: 2000
  node_selectors:
    environment: prod
  hpa:
    minReplicas: 1
    maxReplicas: 2
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 531072824880.dkr.ecr.us-west-2.amazonaws.com/logisticengine-service
  tag: "39778ba"
service:
  type: ClusterIP
secretManager:
  secretId: prod/logisticengine-service
  versionId: ${AWS_SECRET_VERSION_ID}   
ingress:
  enabled: true
  hostName: api.logistics-service.center.quincus.com
  hostName_noram: api.logistics-service.center-noram.quincus.com
  path: /
  nginx_annotations:
    nginx.org/client-max-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
#deployed on Wed Oct 19 15:39:02 UTC 2022
