version: '3'

volumes:
  shipment-v2-new:
    driver: local

services:
  mmysql:
    image: mysql:5.7.30 
    container_name: shipmentv2-mysql-new
    volumes:
      - shipment-v2-new:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipmentv2_local
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    command: --disable-partition-engine-check
