package com.quincus.web.model.error;

public enum QuincusErrorCode {
    VALIDATION_ERROR,
    API_CALL_ERROR,
    USER_DETAILS_ERROR,
    OPERATION_NOT_ALLOWED_ERROR,
    GENERIC_EXCEPTION_ERROR,
    ORGANIZATION_DETAILS_NOT_FOUND_ERROR,
    ACCESS_DENIED_ERROR,
    DATA_LAYER_ERROR,
}
