app:
  region: ap-southeast-1
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 8
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1024
    cpu_limit: 1000
    cpu_required: 500
  sidekiq:
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  qlogger:
    enabled: false
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  namespace: uat
  name: auth
  port: 3000
  env: uat
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: uat
    node-type: on_demand
  preDeployScript:
    enabled: false
    scriptPath: post-deploy/post-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: ""
  schedule: ""
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/auth-quincus-images
  tag: "4a67867"
service:
  type: ClusterIP
secretManager:
  secretId: uat/auth
  versionId: 172755d1-eeb6-45b8-9f42-168f1352f792
ingress:
  enabled: true
  hostName: api.auth.uat.quincus.com
  path: /
  nginx_annotations:    
    nginx.ingress.kubernetes.io/custom-http-errors: "511" # Added 511 just to override nginx error message, basic errors will be handled in app    
redis:
  architecture: standalone
  enabled: false
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: uat
      node-type: on_demand
  auth:
    enabled: false
