replicaCount: 2
app:
  namespace: test
  name: network-management
  port: 8080
  env: test
  image_pull_policy: IfNotPresent
  mem_limit: 0
  mem_required: 1024
  cpu_limit: 0
  cpu_required: 500
  node_selectors:
    environment: test
    node-type: spot
  hpa:
    minReplicas: 2
    maxReplicas: 4
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/network-management-be
  tag: "5.6.0-SNAPSHOT-83d7e73"
service:
  type: ClusterIP
ingress:
  enabled: true
  hostName: api.network-management.test.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "502,503,504"
#deployed on Mon Aug  7 05:35:52 UTC 2023