package com.quincus.networkmanagement.api.constant;

public enum NetworkManagementErrorCode {
    VALIDATION_ERROR,
    INVALID_FORMAT,
    INVALID_REQUEST,
    INVALID_VALUE,
    INVALID_RRULE,
    MISMATCHED_INPUT,
    MISMATCHED_METHOD_ARGUMENT,
    INVALID_FILE,
    INVALID_CONNECTION,
    NODE_NOT_FOUND,
    DUPLICATE_NODE_CODE,
    UPSERT_FACILITY_FAILED,
    DUPLICATE_CONNECTION_CODE,
    CONNECTION_NOT_FOUND,
    JOB_NOT_FOUND,
    JOB_CANCELLATION_NOT_ALLOWED,
    NO_RECORDS_TO_EXPORT,
    INVALID_MME_GRAPH,
    MME_TRAIN_API_FAILED,
    MME_GET_TRAINED_MODEL_API_FAILED
}
