###shipment-nextgen
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-dev
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-dev.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-test
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-test.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-uat
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: uat
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-uat.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-staging
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-staging.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-poc
spec:
  destination:
    name: ''
    namespace: poc
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-poc.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-prod.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-management-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - network-management/values-demo.yaml
  project: network-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true