api-gateway:
  baseUrl: https://api.gateway.test.quincus.com
  flightPath: /flight
  flightSchedulePath: /schedules
  assignVendorDetailsWebhook: /webhook/assignVendorDetails
  updateOrderProgressWebhook: /webhook/updateOrderProgress
  updateOrderAdditionalChargesWebhook: /webhook/updateOrderAdditionalCharges
  s2sToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU0hQVjItdGVzdCIsImp0aSI6ImNjZGVkZTY0LWQwM2MtNDQ2Yi05YjY0LWYwZGZlNmRmNDEyYyIsIm9yZ2FuaXNhdGlvbnMiOltdLCJleHBpcmVzX2F0IjoiIiwiaWF0IjoxNjc4MDg0MjczfQ.PEaXOJC8QkDgs7-xe43HMbGwkGcQHe-KyCbPDleMgmg
  webhookBaseUrl: https://api.gateway-ups.test.quincus.com
  checkInWebhook: /webhook/checkin
apig-retry:
  initialDelay: 1000
  maxDelay: 4000
  maxAttempts: 3
  multiplier: 2