version: '3'

volumes:
  shipment-v2:
    driver: local

services:
  mmysql:
    image: mysql:5.7.30
    container_name: shipmentv2-mysql
    volumes:
      - shipment-v2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipmentv2_local
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    command: --disable-partition-engine-check
