replicaCount: 1
app:
  region: ap-southeast-1
  namespace: staging
  name: dispatch-nextgen
  port: 80
  env: staging
  image_pull_policy: IfNotPresent
  mem_limit: 2048
  mem_required: 1024
  cpu_limit: 1024
  cpu_required: 512
  node_selectors:
    environment: staging
    node-type: spot
  hpa:
    minReplicas: 1
    maxReplicas: 1
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/dispatch-nextgen-be
  tag: "e8d1b5e"
service:
  type: ClusterIP
secretManager:
  secretId: staging/dispatch
  versionId: 2f705a81-e60b-4046-9d9b-19140ff2a3c9
ingress:
  enabled: true
  hostName: api.dispatch-nextgen.staging.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://staging.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform,timeout"
#deployed on Tue Aug  8 03:04:01 UTC 2023
