replicaCount: 1
app:
  region: ap-southeast-1
  namespace: test
  name: dispatch-nextgen
  port: 80
  env: test
  image_pull_policy: IfNotPresent
  mem_limit: 2048
  mem_required: 1024
  cpu_limit: 1024
  cpu_required: 512
  node_selectors:
    environment: test
    node-type: spot
  hpa:
    minReplicas: 1
    maxReplicas: 1
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/dispatch-nextgen-be
  tag: "57220e4"
service:
  type: ClusterIP
secretManager:
  secretId: test/dispatch
  versionId: 00200a76-4682-4302-a612-3df717bfe762
ingress:
  enabled: true
  hostName: api.dispatch-nextgen.test.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://test.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform,timeout"
#deployed on Tue Aug  8 04:38:11 UTC 2023
