feature:
  network-management:
    enabled: true
  authentication:
    enabled: true
  qportal:
    enabled: true
  mme:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/actuator"
  endpoint:
    info:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
  cache:
    enabled: true
