db:
  datasource:
    db: shipment_v2_local
    url: jdbc:mysql://tidb.ctusmuu1r7l.clusters.tidb-cloud.com:4000/${db.datasource.db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: shpv2.root
    password: LZHVVQjtN5qRpMac
    hikari:
      minimumIdle: 50
      maximumPoolSize: 100
      idleTimeout: 60000
      connectionTimeout: 30000
      maxLifetime: 1800000
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    generateDdl: false
    showSql: false
    batchSize: 500
    batchEnable: true
    modelPackages:
      - "com.quincus.shipment.impl.repository.entity"