app:
  region: ap-southeast-1
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 4
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 7000
    mem_required: 3500
    cpu_limit: 2000
    cpu_required: 1000
  sidekiq:
    lifecycle:
      preStop:
       command:
         - /bin/sh
         - -c
         - sidekiq_pid=`ps -aux | grep -i 'sidekiq 6.4.1 current' | awk 'NR==1{print $2}'`;kill -s TSTP -s TERM 
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 10000
    mem_required: 5000
    cpu_limit: 3000
    cpu_required: 1500
  qlogger:
    healthcheck: false
    enabled: false
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 10000
    mem_required: 5000
    cpu_limit: 3000
    cpu_required: 1500
  kafka:
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 12288
    mem_required: 3500
    cpu_limit: 4000
    cpu_required: 2000     
  namespace: perf
  name: pricing
  port: 3000
  env: perf
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: perf
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: pre-deploy/pre-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/pricing-quincus-images
  tag: "661813c"
service:
  type: ClusterIP
secretManager:
  secretId: perf/pricing
  versionId: 7e791449-56c6-48dc-bd0e-ace69bb527e4
ingress:
  enabled: true
  hostName: api.pricing.perf.quincus.com
  hostName_noram: api.pricing.perf-noram.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://ops.apx.group, https://oms.postsales.ups.com, https://oms.expresscritical.ups.com, https://track.postsales.ups.com, https://track.expresscritical.ups.com, https://center.quincus.app, https://dispatch.perf.quincus.com,https://shipment.perf.quincus.com,https://pricing.perf.quincus.com,https://common.perf.quincus.com,https://order.perf.quincus.com,https://perf.quincus.com,https://quincus.perf.qship.quincus.com,https://perf.quincus.app"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform,timeout" 
redis:
  architecture: standalone
  enabled: true
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: perf
      node-type: spot
  auth:
    enabled: false
