###shipment-nextgen
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-dev
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-dev.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-test
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-test.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-uat
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: uat
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-uat.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-staging
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-staging.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-poc
spec:
  destination:
    name: ''
    namespace: poc
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-poc.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-prod.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipment-nextgen-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: charts-springboot
    repoURL: 'git@bitbucket.org:quincus-saas/quincus-k8s-deployments.git'
    targetRevision: master
    helm:
      valueFiles:
        - shipment-nextgen/values-demo.yaml
  project: shipment-nextgen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true