package com.quincus.networkmanagement.impl.attachment.connection;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvBindByPosition;
import lombok.Data;

@Data
public class ConnectionRecord {
    @CsvBindByName(column = "connection_code*")
    @CsvBindByPosition(position = 0)
    private String connectionCode;
    @CsvBindByName(column = "departure_node_code*")
    @CsvBindByPosition(position = 1)
    private String departureNodeCode;
    @CsvBindByName(column = "arrival_node_code*")
    @CsvBindByPosition(position = 2)
    private String arrivalNodeCode;
    @CsvBindByName(column = "schedules*")
    @CsvBindByPosition(position = 3)
    private String schedules;
    @CsvBindByName(column = "duration*")
    @CsvBindByPosition(position = 4)
    private String duration;
    @CsvBindByName(column = "vendor_name*")
    @CsvBindByPosition(position = 5)
    private String vendorName;
    @CsvBindByName(column = "transport_type*")
    @CsvBindByPosition(position = 6)
    private String transportType;
    @CsvBindByName(column = "vehicle_type")
    @CsvBindByPosition(position = 7)
    private String vehicleType;
    @CsvBindByName(column = "active")
    @CsvBindByPosition(position = 8)
    private String active;
    @CsvBindByName(column = "tags")
    @CsvBindByPosition(position = 9)
    private String tags;
    @CsvBindByName(column = "cost")
    @CsvBindByPosition(position = 10)
    private String cost;
    @CsvBindByName(column = "currency_code")
    @CsvBindByPosition(position = 11)
    private String currencyCode;
    @CsvBindByName(column = "max_shipment_length")
    @CsvBindByPosition(position = 12)
    private String maxLength;
    @CsvBindByName(column = "min_shipment_length")
    @CsvBindByPosition(position = 13)
    private String minLength;
    @CsvBindByName(column = "max_shipment_width")
    @CsvBindByPosition(position = 14)
    private String maxWidth;
    @CsvBindByName(column = "min_shipment_width")
    @CsvBindByPosition(position = 15)
    private String minWidth;
    @CsvBindByName(column = "max_shipment_height")
    @CsvBindByPosition(position = 16)
    private String maxHeight;
    @CsvBindByName(column = "min_shipment_height")
    @CsvBindByPosition(position = 17)
    private String minHeight;
    @CsvBindByName(column = "max_shipment_weight")
    @CsvBindByPosition(position = 18)
    private String maxWeight;
    @CsvBindByName(column = "min_shipment_weight")
    @CsvBindByPosition(position = 19)
    private String minWeight;
    @CsvBindByName(column = "max_shipment_single_side")
    @CsvBindByPosition(position = 20)
    private String maxSingleSide;
    @CsvBindByName(column = "min_shipment_single_side")
    @CsvBindByPosition(position = 21)
    private String minSingleSide;
    @CsvBindByName(column = "max_shipment_linear_dim")
    @CsvBindByPosition(position = 22)
    private String maxLinearDim;
    @CsvBindByName(column = "min_shipment_linear_dim")
    @CsvBindByPosition(position = 23)
    private String minLinearDim;
    @CsvBindByName(column = "max_shipment_volume")
    @CsvBindByPosition(position = 24)
    private String maxVolume;
    @CsvBindByName(column = "min_shipment_volume")
    @CsvBindByPosition(position = 25)
    private String minVolume;
    @CsvBindByName(column = "dimension_unit")
    @CsvBindByPosition(position = 26)
    private String dimensionUnit;
    @CsvBindByName(column = "weight_unit")
    @CsvBindByPosition(position = 27)
    private String weightUnit;
    @CsvBindByName(column = "volume_unit")
    @CsvBindByPosition(position = 28)
    private String volumeUnit;
    @CsvBindByName(column = "air_lockout_duration")
    @CsvBindByPosition(position = 29)
    private String airLockoutDuration;
    @CsvBindByName(column = "air_recovery_duration")
    @CsvBindByPosition(position = 30)
    private String airRecoveryDuration;
    @CsvBindByName(column = "max_capacity_count")
    @CsvBindByPosition(position = 31)
    private String maxCapacityCount;
    @CsvBindByName(column = "max_capacity_volume")
    @CsvBindByPosition(position = 32)
    private String maxCapacityVolume;
    @CsvBindByName(column = "max_capacity_weight")
    @CsvBindByPosition(position = 33)
    private String maxCapacityWeight;
    private String failedReason;
}
