security:
  allowed:
    - "/sessions"
    - "/v3/**"
    - "/actuator/**"
    - "/orders/**"
    - "/kafka/**"
    - "/shipments/**"
    - "/costs/**"
    - "/alerts/**"
    - "/flight/**"
    - "/files/**"
    - "/cache/**"
    - "/attachments/**"
  origins:
    - "*"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "OPTIONS"
    - "DELETE"
    - "PATCH"
  headers:
    - "*"
  s2sTokens:
    - name: "ORDER_MODULE" #change?
      value: eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiT1JERVJfTU9EVUxFIiwianRpIjoiZjljNDlhZGEtYTE2MC00MmZmLWFmODEtZmU0NTZiZTBhMTQwIiwiZW52Ijoic3RhZ2luZyIsIm9yZ2FuaXNhdGlvbnMiOltdLCJleHBpcmVzX2F0IjoiIn0.ZqEu9xT3gIwCZqSDGUIR0Vtjwtjwt8EO-EdNf3Q2tNs
    - name: "APIG" #change?
      value: eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic2hpcG1lbnQtbmV4dGdlbi1iZS12MiIsImp0aSI6ImU3Y2M0ZjcxLTlhNzEtNDZjMC1iOTMxLWYyNWZmNjBkNjVkZiIsImVudiI6InN0YWdpbmciLCJvcmdhbml6YXRpb25zIjpbXSwiZXhwaXJlc19hdCI6IjAxLTAxLTIwMjUifQ.f15i8D3kYhFWnuHBahKYeC5G0gegRYqQfVoj-Lx5LmU
