app:
  region: ap-southeast-1
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 4
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1048
    cpu_limit: 1000
    cpu_required: 500
  sidekiq:
    lifecycle:
      preStop:
       command:
         - /bin/sh
         - '-c'
         - |
           kill -TERM $(ps -aux| grep -i 'sidekiq' | awk 'NR==1{print $2}')  
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 400
    mem_required: 200
    cpu_limit: 200
    cpu_required: 100
  qlogger:
    healthcheck: false
    enabled: false
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 400
    mem_required: 200
    cpu_limit: 200
    cpu_required: 100
  racecar:
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 0
    mem_required: 400
    cpu_limit: 0
    cpu_required: 100  
  namespace: test
  name: qship
  port: 3000
  env: test
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: test
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: pre-deploy/pre-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/qship-quincus-images
  tag: "cd5999b"
service:
  type: ClusterIP
secretManager:
  secretId: test/qship
  versionId: 8ba930ae-55c1-4c41-b7a9-8a6b412cb7a8
ingress:
  enabled: true
  hostName: api.qship.test.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dispatch.test.quincus.com, https://shipment.test.quincus.com, https://pricing.test.quincus.com, https://common.test.quincus.com, https://order.test.quincus.com, https://test.quincus.com, https://quincus.test.qship.quincus.com, http://quincus.qship.local.com:3004, http://localhost:3000, https://shp26.test.qship.quincus.com, https://nov72022.test.qship.quincus.com, https://test.quincus.app, https://tsv2.test.qship.quincus.com, https://kafka.test.qship.quincus.com, https://shpv2.test.qship.quincus.com, https://qps.test.qship.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform"  
redis:
  architecture: standalone
  enabled: false
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: test
      node-type: spot
  auth:
    enabled: false