package com.quincus.networkmanagement.impl.attachment.node;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvBindByPosition;
import lombok.Data;

@Data
public class NodeRecord {
    @CsvBindByName(column = "node_code*")
    @CsvBindByPosition(position = 0)
    private String nodeCode;
    @CsvBindByName(column = "node_type*")
    @CsvBindByPosition(position = 1)
    private String nodeType;
    @CsvBindByName(column = "facility_name*")
    @CsvBindByPosition(position = 2)
    private String facilityName;
    @CsvBindByName(column = "vendor_name")
    @CsvBindByPosition(position = 3)
    private String vendorName;
    @CsvBindByName(column = "active")
    @CsvBindByPosition(position = 4)
    private String active;
    @CsvBindByName(column = "description")
    @CsvBindByPosition(position = 5)
    private String description;
    @CsvBindByName(column = "tags")
    @CsvBindByPosition(position = 6)
    private String tags;
    @CsvBindByName(column = "address_line1")
    @CsvBindByPosition(position = 7)
    private String addressLine1;
    @CsvBindByName(column = "address_line2")
    @CsvBindByPosition(position = 8)
    private String addressLine2;
    @CsvBindByName(column = "address_line3")
    @CsvBindByPosition(position = 9)
    private String addressLine3;
    @CsvBindByName(column = "mon_start_time")
    @CsvBindByPosition(position = 10)
    private String monStartTime;
    @CsvBindByName(column = "mon_end_time")
    @CsvBindByPosition(position = 11)
    private String monEndTime;
    @CsvBindByName(column = "mon_processing_time")
    @CsvBindByPosition(position = 12)
    private String monProcessingTime;
    @CsvBindByName(column = "tue_start_time")
    @CsvBindByPosition(position = 13)
    private String tueStartTime;
    @CsvBindByName(column = "tue_end_time")
    @CsvBindByPosition(position = 14)
    private String tueEndTime;
    @CsvBindByName(column = "tue_processing_time")
    @CsvBindByPosition(position = 15)
    private String tueProcessingTime;
    @CsvBindByName(column = "wed_start_time")
    @CsvBindByPosition(position = 16)
    private String wedStartTime;
    @CsvBindByName(column = "wed_end_time")
    @CsvBindByPosition(position = 17)
    private String wedEndTime;
    @CsvBindByName(column = "wed_processing_time")
    @CsvBindByPosition(position = 18)
    private String wedProcessingTime;
    @CsvBindByName(column = "thu_start_time")
    @CsvBindByPosition(position = 19)
    private String thuStartTime;
    @CsvBindByName(column = "thu_end_time")
    @CsvBindByPosition(position = 20)
    private String thuEndTime;
    @CsvBindByName(column = "thu_processing_time")
    @CsvBindByPosition(position = 21)
    private String thuProcessingTime;
    @CsvBindByName(column = "fri_start_time")
    @CsvBindByPosition(position = 22)
    private String friStartTime;
    @CsvBindByName(column = "fri_end_time")
    @CsvBindByPosition(position = 23)
    private String friEndTime;
    @CsvBindByName(column = "fri_processing_time")
    @CsvBindByPosition(position = 24)
    private String friProcessingTime;
    @CsvBindByName(column = "sat_start_time")
    @CsvBindByPosition(position = 25)
    private String satStartTime;
    @CsvBindByName(column = "sat_end_time")
    @CsvBindByPosition(position = 26)
    private String satEndTime;
    @CsvBindByName(column = "sat_processing_time")
    @CsvBindByPosition(position = 27)
    private String satProcessingTime;
    @CsvBindByName(column = "sun_start_time")
    @CsvBindByPosition(position = 28)
    private String sunStartTime;
    @CsvBindByName(column = "sun_end_time")
    @CsvBindByPosition(position = 29)
    private String sunEndTime;
    @CsvBindByName(column = "sun_processing_time")
    @CsvBindByPosition(position = 30)
    private String sunProcessingTime;
    @CsvBindByName(column = "processing_time_unit")
    @CsvBindByPosition(position = 31)
    private String processingTimeUnit;
    @CsvBindByName(column = "max_shipment_length")
    @CsvBindByPosition(position = 32)
    private String maxLength;
    @CsvBindByName(column = "min_shipment_length")
    @CsvBindByPosition(position = 33)
    private String minLength;
    @CsvBindByName(column = "max_shipment_width")
    @CsvBindByPosition(position = 34)
    private String maxWidth;
    @CsvBindByName(column = "min_shipment_width")
    @CsvBindByPosition(position = 35)
    private String minWidth;
    @CsvBindByName(column = "max_shipment_height")
    @CsvBindByPosition(position = 36)
    private String maxHeight;
    @CsvBindByName(column = "min_shipment_height")
    @CsvBindByPosition(position = 37)
    private String minHeight;
    @CsvBindByName(column = "max_shipment_weight")
    @CsvBindByPosition(position = 38)
    private String maxWeight;
    @CsvBindByName(column = "min_shipment_weight")
    @CsvBindByPosition(position = 39)
    private String minWeight;
    @CsvBindByName(column = "dimension_unit")
    @CsvBindByPosition(position = 40)
    private String dimensionUnit;
    @CsvBindByName(column = "weight_unit")
    @CsvBindByPosition(position = 41)
    private String weightUnit;
    @CsvBindByName(column = "volume_unit")
    @CsvBindByPosition(position = 42)
    private String volumeUnit;
    @CsvBindByName(column = "max_capacity_count")
    @CsvBindByPosition(position = 43)
    private String maxCapacityCount;
    @CsvBindByName(column = "max_capacity_volume")
    @CsvBindByPosition(position = 44)
    private String maxCapacityVolume;
    @CsvBindByName(column = "max_capacity_weight")
    @CsvBindByPosition(position = 45)
    private String maxCapacityWeight;
    private String failedReason;
}
