s3-integration:
  region-name: us-east-1
  bucket-name: shipment-nextgen-nonprod-uploads
  base-dir: local
  url-expiry:
    upload: 1440
    read: 10080
  supported-media-types:
    shipment_attachments:
      - image/jpeg
      - image/png
      - application/pdf
    cost_attachments:
      - image/jpeg
      - image/png
  allowed-subdirectories:
    - shipment_attachments
    - cost_attachments
  mock-server: http://localhost:4566/