version: '3'

volumes:
  nw-mysql:
    driver: local

services:
  nw-mysql:
    image: mysql:5.7.30
    container_name: network-management-mysql
    volumes:
      - nw-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: network_management_local
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    command: --disable-partition-engine-check
