replicaCount: 1
app:
  region: ap-southeast-1
  namespace: dev
  name: console-mapping-api
  port: 5000
  env: dev
  image_pull_policy: IfNotPresent
  mem_limit: 4096
  mem_required: 4096
  cpu_limit: 1024
  cpu_required: 1024
  node_selectors:
    environment: dev
    node-type: spot
  hpa:
    minReplicas: 1
    maxReplicas: 1
    averageCPUUtilization: 75
    averageMemoryUtilization: 75
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/console-mapping-api
  tag: "f7280c1"
service:
  type: ClusterIP
secretManager:
  secretId: dev/console-mapping-api
  versionId: 0a2e35a4-1fbf-4fa0-b761-00938bb49fde
ingress:
  enabled: true
  hostName: console-mapping-api.dev.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://mme-console.dev.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,Content-Encoding"
#deployed on Fri Jul 21 13:42:11 UTC 2023
