app:
  region: ap-southeast-1
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 8
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1024
    cpu_limit: 2000
    cpu_required: 1000
  sidekiq:
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  qlogger:
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 1000
    mem_required: 500
    cpu_limit: 200
    cpu_required: 100
  namespace: test
  name: admin
  port: 3000
  env: test
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: test
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: post-deploy/post-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/admin-quincus-images
  tag: "1c5df05"
service:
  type: ClusterIP
secretManager:
  secretId: test/admin
  versionId: 5e3564d8-be58-4cbc-a012-ce2c81886226
ingress:
  enabled: true
  hostName: api.test.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"  
    nginx.ingress.kubernetes.io/custom-http-errors: "511" # Added 511 just to override nginx error message, basic errors will be handled in app
    nginx.ingress.kubernetes.io/enable-cors: "true"    
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dispatch.test-noram.quincus.com, https://shipment.test-noram.quincus.com, https://pricing.test-noram.quincus.com, https://common.test-noram.quincus.com, https://order.test-noram.quincus.com, https://test-noram.quincus.com, https://quincus.test-noram.qship.quincus.com, https://dispatch.test.quincus.com, https://shipment.test.quincus.com, https://pricing.test.quincus.com, https://common.test.quincus.com, https://order.test.quincus.com, https://test.quincus.com, https://test.quincus.app, http://localhost:3000, https://quincus.test.qship.quincus.com, https://SHPV2.test.qship.quincus.com, https://kafka.test.qship.quincus.com, https://nov72022.test.qship.quincus.com, https://tsv2.test.qship.quincus.com, https://qps.test.qship.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform,Access-Control-Allow-Origin"
redis:
  architecture: standalone
  enabled: false
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: test
      node-type: spot
  auth:
    enabled: false
#deployed on Wed Aug  2 08:01:49 UTC 2023
