app:
  region: ap-southeast-1
  puma:
    service_account: "puma-sa"
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 2
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 4096
    mem_required: 2048
    cpu_limit: 2000
    cpu_required: 1000
  sidekiq:
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  qlogger:
    healthcheck: false
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 0
    mem_required: 500
    cpu_limit: 0
    cpu_required: 100
  namespace: demo
  name: admin
  port: 3000
  env: demo
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: demo
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: post-deploy/post-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/admin-quincus-images
  tag: "746f19e"
service:
  type: ClusterIP
secretManager:
  secretId: demo/admin
  versionId: 316b45eb-8e8e-4c20-8fe7-a21c0bc9968e
ingress:
  enabled: true
  hostName: api.demo.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/custom-http-errors: "511" # Added 511 just to override nginx error message, basic errors will be handled in app
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dispatch.preprod.quincus.com, https://shipment.preprod.quincus.com, https://pricing.preprod.quincus.com, https://common.preprod.quincus.com, https://order.preprod.quincus.com, https://preprod.quincus.com, https://quincus.preprod.qship.quincus.com"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,timeout,platform"   
redis:
  architecture: standalone
  enabled: false
  master:
    persistence:
      size: 8Gi
    nodeSelector:
      environment: demo
  auth:
    enabled: false
