qportal:
  s2sToken: YOUR_TOKEN_HERE
  baseUrl: https://api.test.quincus.com/
  packageTypesAPI: api/open_api/v1/package_types/
  partnersAPI: api/v1/partners/
  locationsAPI: api/open_api/v1/locations.json/
  serviceTypeAPI: api/open_api/v1/services.json/
  listUsersAPI: api/open_api/v1/users.json/ # returns name and id, used in listing
  usersAPI: api/v1/users/ # returns more details
  usersGetMyProfileApi: api/v1/users/get_my_profile
  milestonesAPI: api/open_api/v1/milestones.json/
  costTypesAPI: api/v1/cost_types/
  currenciesAPI: api/v1/currencies/
  vehiclesAPI: api/open_api/v1/vehicles/
  notificationAPI: api/open_api/v1/notifications/trigger.json/
  facilitiesAPI: api/v2/facilities/
spring:
  cache:
    type: caffeine
cache:
  expireAfterWriteMinutes: 60
  maximumSize: 10000
  cacheNames: currentUserProfile,partner,locationById,locationByName,partnerByName,vehicle,location,driver,milestones
