feature:
  weight-calculation:
    enabled: true
    db:
      enabled: true
  rate-card:
    enabled: true
    db:
      enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/actuator"
  endpoint:
    info:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true

#springdoc:
#  swagger-ui:
#    path: /costing-api.html
#  api-docs:
#    path: /costing-api-docs