app:
  region: ap-southeast-1
  puma:
    healthcheck: true
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 4
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1024
    cpu_limit: 1024
    cpu_required: 500
  sidekiq:
    lifecycle:
      preStop:
       command:
         - /bin/sh
         - '-c'
         - |
           kill -TERM $(ps -aux| grep -i 'sidekiq' | awk 'NR==1{print $2}')  
    healthcheck: true
    healthcheck_command:
       - /bin/sh
       - '-c'
       - |
         if [ $(($(cat /sys/fs/cgroup/memory/memory.usage_in_bytes)*100/$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes))) -gt 75 ]; then exit 1;fi
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 2
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 2048
    mem_required: 1028
    cpu_limit: 500
    cpu_required: 200
  qlogger:
    enabled: false
    hpa:
      minReplicas: 1
      maxReplicas: 2
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 800
    mem_required: 400
    cpu_limit: 200
    cpu_required: 100
  racecar:
    enabled: true
    hpa:
      minReplicas: 1
      maxReplicas: 1
      averageCPUUtilization: 75
      averageMemoryUtilization: 75
    mem_limit: 0
    mem_required: 400
    cpu_limit: 0
    cpu_required: 100
  namespace: test
  name: shipment
  port: 3000
  env: test
  image_pull_policy: IfNotPresent
  node_selectors:
    environment: test
    node-type: spot
  preDeployScript:
    enabled: true
    scriptPath: post-deploy/post-deploy.sh #script to be ran inside the container
cron:
  enabled: false
  command: "cd /var/app/current; bin/init-config.sh; bundle exec rake open_api_counters:reset --silent"
  schedule: "0 * * * *"
image:
  name: 244836737383.dkr.ecr.ap-southeast-1.amazonaws.com/shipment-quincus-images
  tag: "f7368bd"
service:
  type: ClusterIP
secretManager:
  secretId: test/shipment
  versionId: b697f2e1-6a92-46bb-a16f-6b7e4774da86
ingress:
  enabled: true
  hostName: api.shipment.test.quincus.com
  path: /
  nginx_annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    nginx.ingress.kubernetes.io/custom-http-errors: "500,502,503,504"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dispatch.test.quincus.com, https://shipment.test.quincus.com, https://pricing.test.quincus.com, https://common.test.quincus.com, https://order.test.quincus.com, https://test.quincus.com, https://quincus.test.qship.quincus.com, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,locale,token,platform"
redis:
  architecture: standalone
  enabled: false
  master:
    persistence:
      size: 8Gi
    node_selectors:
      environment: test
      node-type: spot
  auth:
    enabled: false
#deployed on Mon Jul  3 09:35:07 UTC 2023